#ifndef RESISTANCE_DEFS_H
#define RESISTANCE_DEFS_H

#define ASSETCHAINS_MINHEIGHT 128
#define RESISTANCE_ELECTION_GAP 2000
#define ROUNDROBIN_DELAY 61
#define RESISTANCE_ASSETCHAIN_MAXLEN 65
#define RESISTANCE_MAXMEMPOOLTIME 3600

#endif